version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  post_build:
    commands:
      - echo e-server Build completed successfully
artifacts:
  files:
    - target/e-server.jar
  discard-paths: yes
